### ISSUE TITLE
CSVMappingReader is not working correctly

### ISSUE THREAD

**Issue by dobraczka** [AKSW/LIMES-dev#29]
Using DataSetChooser i load DBPLINKEDMDB. Since there are 2 different versions (one with tab-seperated .csv files the other with comma seperated .csv files) the behaviour is different for each.

Using the tab seperated (reference.csv, source.csv, target.csv):
InstanceURIs in the caches have the form \<URI\>
The URIs in the referenceMapping don't have these angle brackets. Therefore I am unable to get Instances out of the caches by using URIs. The problem seems to be line 96 in CSVMappingReader:
```java
m.add(split[0].substring(1, split[0].length() - 1), split[1].substring(1, split[1].length() - 1), 1.0);
```
which works fine for comma-seperated files, but not with tab-seperated. I would propose to change it, given the typical form of the .csv files, by using:
```java
 if(split[0].startsWith("\"")){
     m.add(split[0].substring(1, split[0].length() - 1), split[1].substring(1, split[1].length() - 1), 1.0);  
}else{
     m.add(split[0],split[1],1.0);
}
```

This does not fix another problem in commaseperated files though: For example the line in reference2.csv
```
"<http://dbpedia.org/resource/Elton_John:_Me,_Myself_&_I>","<http://data.linkedmdb.org/resource/film/78002>" 
```
gets split on the wrong comma. Therefore in the AMapping, which is the result of CSVMappingReader reading the file, this looks like this: 
```
[<http://dbpedia.org/resource/Elton_John:_M -> (Myself_&_I>|1.0)]
```
Also the mapping contains the line
```
[iddbpedia -> (idlinkedmdb|1.0)]
```
which probably should not be there.

**Comment by yamalight** [comment]
Can you guys please add a test case for that? So that we can test that it's fixed in controlled manner.

**Comment by dobraczka** [comment]
I've added a test to CSVMappingReaderTest

**Comment by MSherif** [comment]
Fixed

**Comment by yamalight** [comment]
@MSherif build fails due to code errors, can you please check that?

**Comment by MSherif** [comment]
Done, thanks for the email

**Comment by dobraczka** [comment]
The issue is still there the referenceMapping the CSVMappingReader gives back contains the same URIs the Caches contain minus the first and last character. The test I wrote in the CSVMappingReaderTest checks if the Instances in the referenceMapping can be found in the caches so I would suggest not just commenting it out

**Comment by dobraczka** [comment]
I've fixed it
